language: node_js

node_js:
  - "8"

dist: bionic

cache:
  npm: false

before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-12 postgresql-client-12
  - sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
  - sudo service postgresql restart 12  

services: 
  - postgresql

addons:
  postgresql: "12.1"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - PGPASSWORD='' psql -c "CREATE DATABASE teamwork;" -U postgres -h localhost -p 5433
  - PGPASSWORD='' psql -c "CREATE USER root PASSWORD 'password' ;" -U postgres  -h localhost -p 5433
  - PGPASSWORD=password psql -d teamwork -f db.sql -U root -h localhost -p 5433
  - PGPASSWORD=password psql -c "INSERT INTO admin (email, password) VALUES ('postgres@test.com', '$ADMIN_PASSWORD_HASH');" -U root -d teamwork -h localhost -p 5433

after_script:
  - ./cc-test-reporter after-build

deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: teamwork-rest-api
    on: 
      branch: master
