language: node_js

node_js:
  - "8"
env:
  global:
    - CC_TEST_REPORTER_ID=f241b1c0034b615d48967c634592a9b12d57de52f56e3e7c11d9ff9364d08c1f

cache:
  npm: false

before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-12 postgresql-client-12
  - sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
  - sudo service postgresql restart 12  

services: 
  - postgresql

addons:
  postgresql: "12.1"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - PGPASSWORD='' psql -c "CREATE DATABASE teamwork;" -U postgres -h localhost
  - PGPASSWORD='' psql -c "CREATE USER root PASSWORD 'password' ;" -U postgres  -h localhost
  - PGPASSWORD=password psql -d teamwork -f db.sql -U root -h localhost
  - PGPASSWORD=password psql -c "INSERT INTO admin (email, password) VALUES ('postgres@test.com', '$ADMIN_PASSWORD_HASH');" -U root -d teamwork -h localhost

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  - provider: heroku
    api_key: $HEROKU_API_KEY
    app: teamwork-rest-api
    on: 
      branch: master
